name: ifg_mobile_estudante
description: "Aplicativo dos estudantes do Instituto Federal De Goiás."

publish_to: 'none' 

environment:
  sdk:  ^	3.7.2

dev_dependencies:
  flutter_native_splash: ^2.3.1
flutter_native_splash:
  # cor de fundo para Android < 12 e iOS
  color: "#ffffff"
  # imagem principal centralizada
  branding: assets/splash2.png


  # configuração específica para Android 12+
  android_12:
    # imagem que será usada pelo SplashScreen API
    # cor de fundo por trás do ícone no Android 12
    icon_background_color: "#ffffff"
    branding: assets/splash2.png

  # “branding” fica abaixo da image principal


    
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.4
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - .env
    - assets/data/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf 
